#!/usr/bin/env python3
"""Generate the schema-5 key registry from the normative Section-14 block.

The configuration prose is the human-maintained authority.  This utility
extracts its single ``ini`` grammar block and produces a small C++ include used
by the two-pass parser.  The generated file contains no host path or timestamp,
so a clean checkout produces byte-identical parser metadata.

The generator deliberately does *not* infer physics defaults.  It records the
declared value expression (enumeration, REQUIRED, REQUIRED_OR_ZERO, or literal
zero); branch-specific physical validation remains explicit C++ code.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys


MODEL_ROOT = Path(__file__).resolve().parents[1]
SOURCE = MODEL_ROOT / "model" / "configuration_validation.md"
OUTPUT = MODEL_ROOT / "src" / "schema5_registry.inc"


def write_text_lf(path: Path, content: str) -> None:
    """Publish deterministic UTF-8/LF text on Python 3.7 and newer.

    Python 3.8 rejects the newer ``Path.write_text(newline=...)`` signature,
    but its ``Path.open`` API already implements the needed newline control.
    """

    with path.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write(content)


def extract() -> list[tuple[str, str, str]]:
    text = SOURCE.read_text(encoding="utf-8")
    blocks = re.findall(r"```ini\n(.*?)```", text, flags=re.DOTALL)
    # Section 14 also contains a later, explicitly post-schema-5 research
    # sketch.  Only the first block is the released schema-5 grammar; treating
    # a future selector as current would falsely advertise unavailable physics.
    if len(blocks) < 1:
        raise RuntimeError(
            f"expected the normative ini block in {SOURCE}, found none")

    section = ""
    entries: list[tuple[str, str, str]] = []
    seen: set[tuple[str, str]] = set()
    for number, source_line in enumerate(blocks[0].splitlines(), start=1):
        line = source_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("[") and line.endswith("]"):
            section = line[1:-1]
            if not re.fullmatch(
                    r"[a-z][a-z0-9_]*(?:\.[A-Za-z][A-Za-z0-9_]*)*", section):
                raise RuntimeError(f"invalid section {section!r} on grammar line {number}")
            continue
        if "=" not in line or not section:
            raise RuntimeError(f"invalid assignment on grammar line {number}: {line}")
        key, expression = (part.strip() for part in line.split("=", 1))
        if not re.fullmatch(r"[a-z][a-z0-9_]*", key):
            raise RuntimeError(f"invalid key {key!r} on grammar line {number}")
        identity = (section, key)
        if identity in seen:
            raise RuntimeError(f"duplicate grammar key {section}.{key}")
        seen.add(identity)
        entries.append((section, key, expression))
    return entries


def render(entries: list[tuple[str, str, str]]) -> str:
    lines = [
        "// Generated by tools/generate_schema_registry.py. Do not edit.",
        "// Section pattern, key, and normative value expression.",
    ]
    for section, key, expression in entries:
        for token in (section, key, expression):
            if '"' in token or "\\" in token:
                raise RuntimeError(f"cannot render grammar token {token!r}")
        lines.append(f'{{"{section}", "{key}", "{expression}"}},')
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    generated = render(extract())
    if arguments.check:
        try:
            current = OUTPUT.read_text(encoding="utf-8")
        except OSError:
            current = ""
        if current != generated:
            print("SCHEMA5REG ERROR: generated registry is stale", file=sys.stderr)
            return 1
        print("SCHEMA5REG PASS")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    write_text_lf(OUTPUT, generated)
    print(f"generated {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
