#!/usr/bin/env python3
"""Generate the compiled NLGCE-F coefficient arrays from the audited CSVs.

The CSV files are the source artifacts whose SHA-256 identities are fixed by
Sections 20 and 22 of the model specification.  This generator validates the
complete (i,j,k,l) index coverage and emits values in that explicit order; it
does not fit, round, reorder heuristically, or alter any coefficient.
"""

import csv
import io
import pathlib
import sys


ROOT = pathlib.Path(__file__).resolve().parent
DATA = ROOT / "parallel_diffusion_model_data"
OUTPUT = ROOT / "nlgce_f_coefficients.inc"


def load(name):
    values = {}
    with (DATA / name).open(newline="", encoding="ascii") as stream:
        rows = csv.DictReader(stream)
        expected = ["j", "k", "l"] + [f"d_i{i}" for i in range(6)]
        if rows.fieldnames != expected:
            raise ValueError(f"unexpected columns in {name}: {rows.fieldnames}")
        for row in rows:
            j, k, l = (int(row[key]) for key in ("j", "k", "l"))
            for i in range(6):
                key = (i, j, k, l)
                if key in values:
                    raise ValueError(f"duplicate coefficient {key} in {name}")
                values[key] = row[f"d_i{i}"]
    expected_keys = {
        (i, j, k, l)
        for i in range(6)
        for j in range(4)
        for k in range(4)
        for l in range(3)
    }
    if set(values) != expected_keys:
        raise ValueError(f"incomplete coefficient coverage in {name}")
    return values


def emit_array(stream, symbol, values):
    stream.write(f"static constexpr double {symbol}[6][4][4][3] = {{\n")
    for i in range(6):
        stream.write("  {\n")
        for j in range(4):
            stream.write("    {\n")
            for k in range(4):
                row = ", ".join(values[(i, j, k, l)] for l in range(3))
                stream.write(f"      {{{row}}}{',' if k != 3 else ''}\n")
            stream.write(f"    }}{',' if j != 3 else ''}\n")
        stream.write(f"  }}{',' if i != 5 else ''}\n")
    stream.write("};\n")


def main():
    parallel = load("NLGCE_F_2014_parallel.csv")
    perpendicular = load("NLGCE_F_2014_perpendicular.csv")
    stream = io.StringIO(newline="\n")
    stream.write("// Generated from the audited revision-1.4 CSV files.\n")
    stream.write("// Do not edit this file; run generate_nlgce_coefficients.py.\n")
    emit_array(stream, "NlgceFParallel", parallel)
    emit_array(stream, "NlgceFPerpendicular", perpendicular)
    generated = stream.getvalue()
    if "--check" in sys.argv[1:]:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="ascii") != generated:
            print(f"{OUTPUT.name} is not synchronized with the audited CSV files",
                  file=sys.stderr)
            return 1
        print(f"PASS {OUTPUT.name}: exact CSV index/literal coverage")
    else:
        OUTPUT.write_text(generated, encoding="ascii", newline="\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
