#include "test_framework.hpp"

#include <cstdlib>
#include <iostream>

// COV01 is an orchestration test because compiler coverage counters must be
// generated by a fresh executable.  The child marker makes the instrumented
// executable record this registry slot as exercised without recursively
// launching another build; all other registered tests still execute normally.
void test_cov01(swcme_test::Context& context) {
  std::cout << "COV01 line and branch coverage closure\n";
  const char* child=std::getenv("SWCME_COV01_CHILD");
  if (child!=nullptr && child[0]=='1' && child[1]=='\0') {
    context.expect_true(true,"instrumented COV01 child marker recognized");
    return;
  }

  const int result=std::system("make --no-print-directory cov01-coverage");
  context.expect_true(result==0,
      "fresh source-only line/branch coverage gate succeeds");
}
